/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function test(a: number, b: number): void;
export function __wbg_location_free(a: number): void;
export function __wbg_get_location_0(a: number): number;
export function __wbg_set_location_0(a: number, b: number): void;
export function __wbg_get_location_1(a: number): number;
export function __wbg_set_location_1(a: number, b: number): void;
export function __wbg_get_location_2(a: number): number;
export function __wbg_set_location_2(a: number, b: number): void;
export function __wbg_graphicsmatrix_free(a: number): void;
export function graphicsmatrix_create_camera_matrix(a: number, b: number, c: number, d: number): number;
export function graphicsmatrix_create_model_inverse_transpose_matrix(a: number, b: number, c: number): number;
export function graphicsmatrix_create_model_view_projection_matrix(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): number;
export function __wbg_set_translation_0(a: number, b: number): void;
export function __wbg_set_translation_1(a: number, b: number): void;
export function __wbg_set_translation_2(a: number, b: number): void;
export function __wbg_set_rotation_0(a: number, b: number): void;
export function __wbg_set_rotation_1(a: number, b: number): void;
export function __wbg_set_rotation_2(a: number, b: number): void;
export function __wbg_get_translation_0(a: number): number;
export function __wbg_get_translation_1(a: number): number;
export function __wbg_get_translation_2(a: number): number;
export function __wbg_get_rotation_0(a: number): number;
export function __wbg_get_rotation_1(a: number): number;
export function __wbg_get_rotation_2(a: number): number;
export function __wbg_translation_free(a: number): void;
export function __wbg_rotation_free(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
